// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDisks():Promise<Array<{[key: string]: any}>>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectory(arg1:string):Promise<Array<{[key: string]: string}>>;

export function ProcessFile():Promise<string>;

export function Search_Directory(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<Array<main.DirectoryChild>>;
