// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessDir(arg1) {
  return window['go']['main']['App']['ProcessDir'](arg1);
}

export function ProcessFile() {
  return window['go']['main']['App']['ProcessFile']();
}
