// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDisks() {
  return window['go']['main']['App']['GetDisks']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function ProcessFile() {
  return window['go']['main']['App']['ProcessFile']();
}

export function Search_Directory(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Search_Directory'](arg1, arg2, arg3, arg4, arg5);
}
