// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDisks():Promise<Array<main.Drive>>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectory(arg1:string):Promise<Array<string>>;

export function ProcessFile():Promise<string>;
